### ISSUE TITLE
How to change the animation when it shows up?

### ISSUE THREAD

**Issue by aetherwu** [mahmudahsan/SwiftUI-Action-Sheet-Custom-View-Card#2]
I am so sorry to ask for you time and attention.
But would you mine please hit my by any advise on implemetation?

**Comment by mahmudahsan** [comment]
Hi,
In this file https://github.com/mahmudahsan/SwiftUI-Action-Sheet-Custom-View-Card/blob/main/Sources/ActionSheetCustomViewCard.swift, line number 152 to 163

`    public var body: some View {
        Group {
            if isShowing {
                bodyContent
            }
        }
        .animation(.default)
        .onReceive(Just(isShowing), perform: { isShowing in
            onUpdateIsShowing(isShowing)
        })
        .edgesIgnoringSafeArea(.all)
    }`

You can change the animation. You can fork the repo, and update that `.animation()` and use it in your app.

If you can update the library so that we can set animation on fly, please submit a pull request.
